<a href="https://colab.research.google.com/github/sakshi-runghe/Python_Practice/blob/main/EDA_NumPy_Practice_Questions_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#PRACTISE QUESTIONS
#NUMPY
#1.Create a 1-D NumPy array containing numbers from 1 to 100.
import numpy as np
data=np.arange(1,101)
data

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
#2.Create a 2-D array of shape(3,4) filled with zeroes.
data=np.zeros((3,4))
data

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#3.Create an array of 5 equally spaced numbers between 0 and 1
data=np.linspace(0,1,5)
data

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#4.Find the data type, shape and dimensions of any array
data=np.array([[1,2,3],[3,4,5]])
print(data.dtype)
print(data.shape)
print(data.ndim)

int64
(2, 3)
2


In [ ]:
#5.Convert a Python list [1,2,3,4] into a NumPy array
data=np.array([1,2,3,4])
data


array([1, 2, 3, 4])

In [ ]:
#6.Create a NumPy array and change its data type to float
data=np.array([1,2,3,4])
data=data.astype(float)
data

array([1., 2., 3., 4.])

In [ ]:
#7.Create a identity matrix of size 4*4
data=np.eye(4,4)
data

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#8.Generate a random array of size 5
from numpy import random
data=np.random.rand(5)
data

3

In [ ]:
#9.Access the third element of 1-D array
data=np.array([1,2,3,4,5])
print(data[2])

3


In [ ]:
#10.Access the element in 2nd row, 3rd column of a 2-D array
data=np.array([[1,2,5],
               [3,4,6]])
print(data[1,2])

6


In [ ]:
#11.Extract all even numbers from an array
data=np.array([1,2,3,4,5,6,7,8,9])
data[data%2==0]


array([2, 4, 6, 8])

In [ ]:
#12.Reverse a NumPy array
data=np.array([1,2,3,4])
print(data[::-1])

[4 3 2 1]


In [ ]:
#13.Find the maximum and minimum value in a array
data=np.array([1,2,3,4,7,2,2,8,9])
print(data.max())
print(data.min())


9
1


In [ ]:
#14.Replace all values greater than 10 with 10
data=np.array([1,2,3,10,12,16,2,7,8])
data[data>10]=10
data

array([ 1,  2,  3, 10, 10, 10,  2,  7,  8])

In [ ]:
#15.Perform element wise addition of two arrays
data1=np.array([1,2,3,4])
data2=np.array([5,6,7,8])
print(data1+data2)

[ 6  8 10 12]


In [ ]:
#16.Multiply all elements of an array by 5 without using a loop.
data=np.array([1,2,3,4,5,6,7,8,9,10])
i=0
print(data[i]*5)
i+=1




5


In [ ]:
#17.Reshape a 1-D array of size 12 into a (3,4) matrix
data=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(data.reshape(3,4))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#18.Flatten a 2-D array into 1-D
data=np.array([[1,2,3,4],[4,3,2,1],[4,2,6,7]])
print(data.flatten())

[1 2 3 4 4 3 2 1 4 2 6 7]


In [ ]:
#19.Find the sum of each row in a 2-D array
data=np.array([[1,2,3,4],[4,3,2,1],[6,7,8,3]])
print(data.sum())

44


In [ ]:
#20.Find the mean of each column in a 2-D array
data=np.array([[1,2,3,4],[6,3,4,2],[6,8,3,4]])
print(data.mean())

3.8333333333333335
